export const data = [
  {
    id: 1,
    name: "Avatar 2",
    released: "16 December 2022 (Expected)",
    plot: "A sequel to the 2009 film 'Avatar,' exploring new adventures on the planet Pandora.",
    type: "soon",
    image: "/images/film1.jpg",
  },
  {
    id: 2,
    name: "Dune Part Two",
    released: "20 October 2023 (Expected)",
    plot: "The second part of the adaptation of Frank Herbert's science fiction novel 'Dune.'",
    type: "soon",
    image: "/images/film2.jpg",
  },
  {
    id: 3,
    name: "Star Wars: Episode X",
    released: "TBD",
    plot: "The next installment in the Star Wars saga, continuing the epic space opera.",
    type: "soon",
    image: "/images/film3.jpg",
  },
  {
    id: 4,
    name: "Indiana Jones 5",
    released: "29 June 2023 (Expected)",
    plot: "The fifth installment in the Indiana Jones series, featuring the iconic archaeologist on a new adventure.",
    type: "soon",
    image: "/images/film4.jpg",
  },
  {
    id: 5,
    name: "The Matrix 4",
    released: "22 December 2022",
    plot: "Neo returns in the fourth installment of the Matrix series, exploring new dimensions of reality.",
    type: "released",
    image: "/images/film5.jpg",
  },
  {
    id: 6,
    name: "Jurassic World: Dominion",
    released: "9 June 2023 (Expected)",
    plot: "The latest entry in the Jurassic Park franchise, where dinosaurs continue to roam the Earth.",
    type: "soon",
    image: "/images/film6.jpg",
  },
  {
    id: 7,
    name: "Black Panther: Wakanda Forever",
    released: "8 November 2022",
    plot: "A sequel to Black Panther, exploring the legacy of T'Challa and the future of Wakanda.",
    type: "released",
    image: "/images/film7.jpg",
  },
  {
    id: 8,
    name: "No Time to Die",
    released: "8 October 2021",
    plot: "The latest James Bond film, featuring 007 on a mission to thwart a dangerous new villain.",
    type: "released",
    image: "/images/film8.jpg",
  },
  {
    id: 9,
    name: "Spider-Man: No Way Home",
    released: "17 December 2021",
    plot: "Spider-Man faces multiverse chaos as he teams up with other Spider-People to save their realities.",
    type: "released",
    image: "/images/film9.jpg",
  },
  {
    id: 10,
    name: "The Suicide Squad",
    released: "5 August 2021",
    plot: "A group of antiheroes is sent on a dangerous mission by Amanda Waller, leading to mayhem and humor.",
    type: "released",
    image: "/images/film10.jpg",
  },
  {
    id: 11,
    name: "The Batman",
    released: "4 March 2022",
    plot: "A dark and gritty portrayal of Batman as he unravels a mystery in Gotham City.",
    type: "released",
    image: "/images/film11.jpg",
  },
  {
    id: 12,
    name: "Avatar 3",
    released: "20 December 2024 (Expected)",
    plot: "Continuing the saga on Pandora, with new challenges for the Na'vi.",
    type: "soon",
    image: "/images/film12.jpg",
  },
  {
    id: 13,
    name: "Guardians of the Galaxy Vol. 3",
    released: "5 May 2023 (Expected)",
    plot: "The third installment of the cosmic adventures of the Guardians of the Galaxy.",
    type: "soon",
    image: "/images/film13.jpg",
  },
  {
    id: 14,
    name: "Wonder Woman 3",
    released: "21 December 2023 (Expected)",
    plot: "Diana Prince returns for another epic adventure as Wonder Woman.",
    type: "soon",
    image: "/images/film14.jpg",
  },
  {
    id: 15,
    name: "Avatar 4",
    released: "18 December 2026 (Expected)",
    plot: "The journey on Pandora continues with more mysteries and discoveries.",
    type: "soon",
    image: "/images/film15.jpg",
  },
  {
    id: 16,
    name: "Fantastic Beasts: The Secrets of Dumbledore",
    released: "15 April 2022",
    plot: "Newt Scamander faces new challenges in the wizarding world as he seeks Dumbledore's secrets.",
    type: "released",
    image: "/images/film16.jpg",
  },
  {
    id: 17,
    name: "Mission: Impossible 7",
    released: "28 May 2022",
    plot: "Ethan Hunt returns for another high-stakes mission filled with action and intrigue.",
    type: "released",
    image: "/images/film17.jpg",
  },
  {
    id: 18,
    name: "The Flash",
    released: "4 November 2022",
    plot: "Barry Allen, aka The Flash, explores the multiverse in a thrilling adventure.",
    type: "released",
    image: "/images/film18.jpg",
  },
  {
    id: 19,
    name: "Thor: Love and Thunder",
    released: "6 May 2022",
    plot: "Thor faces new challenges and reunites with Jane Foster as she becomes Thor herself.",
    type: "released",
    image: "/images/film19.jpg",
  },
  {
    id: 20,
    name: "Doctor Strange in the Multiverse of Madness",
    released: "6 May 2022",
    plot: "Doctor Strange battles mystical threats across the multiverse.",
    type: "released",
    image: "/images/film20.jpg",
  },
];
